/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WithdrawRouteImport } from './routes/withdraw'
import { Route as TransferRouteImport } from './routes/transfer'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AddMoneyRouteImport } from './routes/add-money'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NotificationsPreferencesRouteImport } from './routes/notifications.preferences'
import { Route as NotificationsHistoryRouteImport } from './routes/notifications.history'

const WithdrawRoute = WithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const TransferRoute = TransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AddMoneyRoute = AddMoneyRouteImport.update({
  id: '/add-money',
  path: '/add-money',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsPreferencesRoute =
  NotificationsPreferencesRouteImport.update({
    id: '/notifications/preferences',
    path: '/notifications/preferences',
    getParentRoute: () => rootRouteImport,
  } as any)
const NotificationsHistoryRoute = NotificationsHistoryRouteImport.update({
  id: '/notifications/history',
  path: '/notifications/history',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-money': typeof AddMoneyRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/transactions': typeof TransactionsRoute
  '/transfer': typeof TransferRoute
  '/withdraw': typeof WithdrawRoute
  '/notifications/history': typeof NotificationsHistoryRoute
  '/notifications/preferences': typeof NotificationsPreferencesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-money': typeof AddMoneyRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/transactions': typeof TransactionsRoute
  '/transfer': typeof TransferRoute
  '/withdraw': typeof WithdrawRoute
  '/notifications/history': typeof NotificationsHistoryRoute
  '/notifications/preferences': typeof NotificationsPreferencesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-money': typeof AddMoneyRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/transactions': typeof TransactionsRoute
  '/transfer': typeof TransferRoute
  '/withdraw': typeof WithdrawRoute
  '/notifications/history': typeof NotificationsHistoryRoute
  '/notifications/preferences': typeof NotificationsPreferencesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-money'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/register'
    | '/transactions'
    | '/transfer'
    | '/withdraw'
    | '/notifications/history'
    | '/notifications/preferences'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-money'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/register'
    | '/transactions'
    | '/transfer'
    | '/withdraw'
    | '/notifications/history'
    | '/notifications/preferences'
  id:
    | '__root__'
    | '/'
    | '/add-money'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/register'
    | '/transactions'
    | '/transfer'
    | '/withdraw'
    | '/notifications/history'
    | '/notifications/preferences'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddMoneyRoute: typeof AddMoneyRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  TransactionsRoute: typeof TransactionsRoute
  TransferRoute: typeof TransferRoute
  WithdrawRoute: typeof WithdrawRoute
  NotificationsHistoryRoute: typeof NotificationsHistoryRoute
  NotificationsPreferencesRoute: typeof NotificationsPreferencesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/withdraw': {
      id: '/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof WithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfer': {
      id: '/transfer'
      path: '/transfer'
      fullPath: '/transfer'
      preLoaderRoute: typeof TransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-money': {
      id: '/add-money'
      path: '/add-money'
      fullPath: '/add-money'
      preLoaderRoute: typeof AddMoneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/preferences': {
      id: '/notifications/preferences'
      path: '/notifications/preferences'
      fullPath: '/notifications/preferences'
      preLoaderRoute: typeof NotificationsPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/history': {
      id: '/notifications/history'
      path: '/notifications/history'
      fullPath: '/notifications/history'
      preLoaderRoute: typeof NotificationsHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddMoneyRoute: AddMoneyRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  TransactionsRoute: TransactionsRoute,
  TransferRoute: TransferRoute,
  WithdrawRoute: WithdrawRoute,
  NotificationsHistoryRoute: NotificationsHistoryRoute,
  NotificationsPreferencesRoute: NotificationsPreferencesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
